---
- name: installation de serveur avec docker
  hosts: web
  remote_user: root
  
  vars_files:
    - variable.yml

  pre_tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: update server
      yum: name=* state=latest            
    - name: installation de docker
      yum: name={{ item }} disable_gpg_check=yes 
      with_items:
          - vim
          - python-pip
          - docker 
  
    - name: Install Docker-py
      pip: name=docker-py
    - name: affichier variable
      debug:
        msg: "les adresses ip sont {{ host1 }} "
  roles:
    - docker
...
